DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS WorkerStatus CASCADE;

DROP TYPE IF EXISTS TicketStatus CASCADE;

DROP TABLE IF EXISTS workers CASCADE;

DROP TABLE IF EXISTS tickets CASCADE;

DROP TABLE IF EXISTS stores CASCADE;