DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS DoctorStatus CASCADE;

DROP TYPE IF EXISTS TicketStatus CASCADE;

DROP TABLE IF EXISTS doctors CASCADE;

DROP TABLE IF EXISTS tickets CASCADE;

DROP TABLE IF EXISTS locations CASCADE;